import React, { createContext, useContext, useState } from "react";

export type Lang = "en" | "cy" | "hi" | "ta";

export const languages: { code: Lang; label: string; flag: string; nativeLabel: string }[] = [
  { code: "en", label: "English",  flag: "🇬🇧", nativeLabel: "English"  },
  { code: "cy", label: "Welsh",    flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", nativeLabel: "Cymraeg"  },
  { code: "hi", label: "Hindi",    flag: "🇮🇳", nativeLabel: "हिंदी"    },
  { code: "ta", label: "Tamil",    flag: "🇮🇳", nativeLabel: "தமிழ்"    },
];

const translations: Record<Lang, Record<string, string>> = {
  en: {
    nav_home: "Home",
    nav_products: "Products",
    nav_whyus: "Why Choose Us",
    nav_about: "About",
    nav_blog: "Blog",
    nav_media: "Media",
    nav_contact: "Contact",
    hero_badge: "Clean Label · Naturally Sourced · Crafted in Wales",
    hero_title1: "Pure Goodness",
    hero_title2: "for All",
    hero_sub: "Naturally sourced, additive-free breakfast cereals crafted in Wales, inspired by global culinary traditions and designed for modern nutritional standards.",
    hero_cta1: "Explore Products",
    hero_cta2: "Our Story",
    why_label: "Why HNM",
    why_heading: "Ingredients You Can Trust",
    feat1_title: "Natural Ingredients",
    feat1_desc: "Every ingredient is naturally sourced with no artificial additives or preservatives.",
    feat2_title: "No Preservatives",
    feat2_desc: "Clean formulations free from synthetic chemicals and artificial flavourings.",
    feat3_title: "A Good Source of Protein",
    feat3_desc: "Formulated with plant-based protein to support a nutritious morning.",
    feat4_title: "Family Focused",
    feat4_desc: "Wholesome products designed for the whole family, crafted with care in Cardiff, Wales.",
    product_label: "Our Flagship Product",
    product_heading: "Multi Grain Cereal",
    product_desc: "Crafted in Wales from premium multi grain blend sourced from organic farms (certification in progress), our cereal is designed to deliver strong nutritional value. Developed to be rich in vitamins and plant protein, and completely free from artificial additives.",
    product_view: "View Full Range",
    cta_heading: "Ready to Experience Clean Nutrition?",
    cta_sub: "Get in touch to learn about our products, retail partnerships, or catering enquiries.",
    cta_btn: "Get in Touch",
    footer_tagline: "Clean-label, naturally sourced breakfast cereals crafted in Wales to meet modern nutritional standards.",
    footer_products: "Products",
    footer_company: "Company",
    footer_contact: "Contact",
    footer_copyright: "© 2026 HNM Food Group Ltd. All rights reserved. Crafted in Wales.",
    follow_us: "Follow Us",
    contact_title: "Get in Touch",
    contact_sub: "Whether you're interested in retail partnerships, product enquiries, or airline catering, we'd love to hear from you.",
  },
  cy: {
    nav_home: "Cartref",
    nav_products: "Cynhyrchion",
    nav_whyus: "Pam Dewis Ni",
    nav_about: "Amdanom Ni",
    nav_blog: "Blog",
    nav_media: "Cyfryngau",
    nav_contact: "Cysylltu",
    hero_badge: "Label Glân · Ffynhonnell Naturiol · Wedi'i Grefftio yng Nghymru",
    hero_title1: "Daioni Pur",
    hero_title2: "i Bawb",
    hero_sub: "Grawnfwydydd brecwast wedi'u ffynhonnell yn naturiol, heb ychwanegion, wedi'u crefftio yng Nghymru ac wedi'u hysbrydoli gan draddodiadau coginio byd-eang.",
    hero_cta1: "Archwilio Cynhyrchion",
    hero_cta2: "Ein Stori",
    why_label: "Pam HNM",
    why_heading: "Cynhwysion y Gallwch Chi Ymddiried Ynddynt",
    feat1_title: "Cynhwysion Naturiol",
    feat1_desc: "Mae pob cynhwysyn wedi'i gael yn naturiol heb unrhyw ychwanegion artiffisial na chadwolion.",
    feat2_title: "Dim Cadwolion",
    feat2_desc: "Fformwleiddiadau glân rhydd o gemegau synthetig a blasyddion artiffisial.",
    feat3_title: "Ffynhonnell Dda o Brotein",
    feat3_desc: "Wedi'i fformwleiddio â phrotein planhigion i gynnal brecwast maethlon. (Fformwleiddiad targed)",
    feat4_title: "Canolbwyntio ar y Teulu",
    feat4_desc: "Cynhyrchion iachus wedi'u cynllunio ar gyfer y teulu cyfan, wedi'u crefftio â gofal yng Nghaerdydd, Cymru.",
    product_label: "Ein Cynnyrch Blaenllaw",
    product_heading: "Grawnfwyd Aml-rawn",
    product_desc: "Wedi'i grefftio yng Nghymru o rawnfwydau miled premiwm o ffermydd organig (ardystiad ar y gweill), mae ein grawnfwyd wedi'i gynllunio i ddarparu gwerth maethol cryf. Heb ychwanegion artiffisial.",
    product_view: "Gweld yr Ystod Lawn",
    cta_heading: "Barod i Brofi Maeth Glân?",
    cta_sub: "Cysylltwch â ni i ddysgu am ein cynhyrchion, partneriaethau manwerthu, neu ymholiadau arlwyo.",
    cta_btn: "Cysylltu",
    footer_tagline: "Grawnfwydydd brecwast label glân wedi'u crefftio yng Nghymru i fodloni safonau maeth modern.",
    footer_products: "Cynhyrchion",
    footer_company: "Cwmni",
    footer_contact: "Cysylltu",
    footer_copyright: "© 2026 HNM Food Group Ltd. Cedwir pob hawl. Wedi'i Grefftio yng Nghymru.",
    follow_us: "Dilynwch Ni",
    contact_title: "Cysylltwch â Ni",
    contact_sub: "P'un a oes gennych ddiddordeb mewn partneriaethau manwerthu, ymholiadau cynnyrch, neu arlwyo awyrennau, byddem wrth ein bodd yn clywed gennych.",
  },
  hi: {
    nav_home: "होम",
    nav_products: "उत्पाद",
    nav_whyus: "हमें क्यों चुनें",
    nav_about: "हमारे बारे में",
    nav_blog: "ब्लॉग",
    nav_media: "मीडिया",
    nav_contact: "संपर्क",
    hero_badge: "क्लीन लेबल · प्राकृतिक स्रोत · वेल्स में निर्मित",
    hero_title1: "शुद्ध अच्छाई",
    hero_title2: "सभी के लिए",
    hero_sub: "वेल्स में तैयार, प्राकृतिक रूप से प्राप्त, बिना योजक के नाश्ता अनाज, आधुनिक पोषण मानकों के लिए तैयार और वैश्विक पाक परंपराओं से प्रेरित।",
    hero_cta1: "उत्पाद देखें",
    hero_cta2: "हमारी कहानी",
    why_label: "एचएनएम क्यों",
    why_heading: "सामग्री जिन पर आप भरोसा कर सकते हैं",
    feat1_title: "प्राकृतिक सामग्री",
    feat1_desc: "हर सामग्री प्राकृतिक रूप से प्राप्त की जाती है, बिना किसी कृत्रिम योजक या परिरक्षकों के।",
    feat2_title: "कोई परिरक्षक नहीं",
    feat2_desc: "सिंथेटिक रसायनों और कृत्रिम स्वादों से मुक्त स्वच्छ फॉर्मूलेशन।",
    feat3_title: "प्रोटीन का अच्छा स्रोत",
    feat3_desc: "पौधे-आधारित प्रोटीन के साथ तैयार, पौष्टिक सुबह के लिए। (लक्ष्य फॉर्मूलेशन)",
    feat4_title: "परिवार केंद्रित",
    feat4_desc: "वेल्स, कार्डिफ में प्यार से तैयार, पूरे परिवार के लिए उत्पाद।",
    product_label: "हमारा प्रमुख उत्पाद",
    product_heading: "मल्टी ग्रेन अनाज",
    product_desc: "वेल्स में तैयार, जैविक खेतों के प्रीमियम बाजरे के दानों से (प्रमाणीकरण प्रक्रिया में), हमारा अनाज मजबूत पोषण मूल्य प्रदान करने के लिए डिज़ाइन किया गया है। कृत्रिम योजकों से पूर्णतः मुक्त।",
    product_view: "पूरी रेंज देखें",
    cta_heading: "स्वच्छ पोषण का अनुभव करने के लिए तैयार हैं?",
    cta_sub: "हमारे उत्पादों, खुदरा साझेदारी, या केटरिंग जांच के बारे में जानने के लिए संपर्क करें।",
    cta_btn: "संपर्क करें",
    footer_tagline: "वेल्स में तैयार, आधुनिक पोषण मानकों के लिए प्राकृतिक रूप से प्राप्त नाश्ता अनाज।",
    footer_products: "उत्पाद",
    footer_company: "कंपनी",
    footer_contact: "संपर्क",
    footer_copyright: "© 2026 एचएनएम फूड ग्रुप लिमिटेड। सर्वाधिकार सुरक्षित। वेल्स में निर्मित।",
    follow_us: "हमें फॉलो करें",
    contact_title: "संपर्क करें",
    contact_sub: "चाहे आप खुदरा साझेदारी, उत्पाद पूछताछ, या एयरलाइन केटरिंग में रुचि रखते हों, हम आपसे सुनना चाहेंगे।",
  },
  ta: {
    nav_home: "முகப்பு",
    nav_products: "தயாரிப்புகள்",
    nav_whyus: "ஏன் நாங்கள்",
    nav_about: "எங்களைப் பற்றி",
    nav_blog: "வலைப்பதிவு",
    nav_media: "ஊடகம்",
    nav_contact: "தொடர்பு",
    hero_badge: "சுத்தமான லேபிள் · இயற்கை ஆதாரம் · வேல்ஸில் தயாரிக்கப்பட்டது",
    hero_title1: "தூய நன்மை",
    hero_title2: "அனைவருக்கும்",
    hero_sub: "வேல்ஸில் தயாரிக்கப்பட்ட, இயற்கையாக பெறப்பட்ட, சேர்க்கைகள் இல்லாத காலை உணவு தானியங்கள், நவீன ஊட்டச்சத்து தரங்களுக்காக உருவாக்கப்பட்டது.",
    hero_cta1: "தயாரிப்புகளை காண்க",
    hero_cta2: "எங்கள் கதை",
    why_label: "ஏன் HNM",
    why_heading: "நம்பகமான பொருட்கள்",
    feat1_title: "இயற்கை பொருட்கள்",
    feat1_desc: "ஒவ்வொரு பொருளும் இயற்கையாக பெறப்படுகிறது, செயற்கை சேர்க்கைகள் அல்லது பதப்படுத்திகள் இல்லாமல்.",
    feat2_title: "பதப்படுத்திகள் இல்லை",
    feat2_desc: "செயற்கை இரசாயனங்கள் மற்றும் செயற்கை சுவைகளிலிருந்து விடுபட்ட சுத்தமான சூத்திரங்கள்.",
    feat3_title: "புரதத்தின் நல்ல மூலம்",
    feat3_desc: "ஊட்டமான காலை உணவை ஆதரிக்க தாவர அடிப்படையிலான புரதத்துடன் உருவாக்கப்பட்டது. (இலக்கு சூத்திரம்)",
    feat4_title: "குடும்ப கவனம்",
    feat4_desc: "கார்டிஃப், வேல்ஸில் அன்புடன் தயாரிக்கப்பட்ட, குடும்பம் முழுவதும் ஏற்ற தயாரிப்புகள்.",
    product_label: "எங்கள் முன்னணி தயாரிப்பு",
    product_heading: "பல தானியங்கள்",
    product_desc: "வேல்ஸில் தயாரிக்கப்பட்ட, கரிம பண்ணைகளிலிருந்து (சான்றிதழ் நடைமுறையில்) உயரிய தினை தானியங்களை கொண்ட எங்கள் தானியம் வலுவான ஊட்டச்சத்து மதிப்பை வழங்க வடிவமைக்கப்பட்டுள்ளது. செயற்கை சேர்க்கைகள் இல்லாதது.",
    product_view: "முழு வரிசையை காண்க",
    cta_heading: "சுத்தமான ஊட்டச்சத்தை அனுபவிக்க தயாரா?",
    cta_sub: "சில்லறை கூட்டாண்மைகள், தயாரிப்பு விசாரணைகள் அல்லது விமான சேவை பற்றி அறிய தொடர்பு கொள்ளுங்கள்.",
    cta_btn: "தொடர்பு கொள்ளுங்கள்",
    footer_tagline: "வேல்ஸில் தயாரிக்கப்பட்ட, நவீன ஊட்டச்சத்து தரங்களை பூர்த்தி செய்யும் சுத்தமான லேபிள் காலை உணவு தானியங்கள்.",
    footer_products: "தயாரிப்புகள்",
    footer_company: "நிறுவனம்",
    footer_contact: "தொடர்பு",
    footer_copyright: "© 2026 HNM ஃபுட் குரூப் லிமிடெட். அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை. வேல்ஸில் தயாரிக்கப்பட்டது.",
    follow_us: "எங்களை பின்தொடரவும்",
    contact_title: "தொடர்பு கொள்ளுங்கள்",
    contact_sub: "சில்லறை கூட்டாண்மைகள், தயாரிப்பு விசாரணைகள் அல்லது விமான சேவையில் ஆர்வம் இருந்தாலும், நாங்கள் உங்களிடமிருந்து கேட்க விரும்புகிறோம்.",
  },
};

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
});

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLang] = useState<Lang>("en");
  const t = (key: string) => translations[lang][key] ?? translations["en"][key] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
